on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Before Printing Folder action'
        run: ls

      - uses: actions/checkout@v3  

      - name: 'After Printing Folder action'
        run: ls 